apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  name: konami-buttonpresses
  labels:
    eventstreams.ibm.com/cluster: my-kafka-cluster
spec:
  config:
    min.insync.replicas: '1'
    retention.bytes: '50000000'
  partitions: 1
  replicas: 1
  topicName: KONAMI.BUTTONPRESSES
---
apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  name: konami-cheats
  labels:
    eventstreams.ibm.com/cluster: my-kafka-cluster
spec:
  config:
    min.insync.replicas: '1'
    retention.bytes: '50000000'
  partitions: 1
  replicas: 1
  topicName: KONAMI.CHEATS
---
apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  name: connect.dlq
  labels:
    eventstreams.ibm.com/cluster: my-kafka-cluster
spec:
  config:
    min.insync.replicas: '1'
    retention.bytes: '5000000'
  partitions: 1
  replicas: 1
  topicName: CONNECT.DLQ
